muffinprojects/muffinproject/muffinapp/urls.py
from django.urls import path
from . import views
app_name='muffinapp'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail')
   ]

muffinprojects/muffinproject/muffinproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('muffinapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

muffinprojects/muffinproject/muffinapp/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('muffinapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('muffinapp:prodCatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

muffinprojects/muffinproject/muffinapp/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.Get.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})
def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

muffinprojects/muffinproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">


    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color:#191819">
<div class="container-fluid">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"</script>

</body>
</html>

muffinprojects/muffinproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to The Muffin House website where you can satisfy your cravings.
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -THE MUFFIN HOUSE
    {% else %}
        Purchase the best Sweets in the muffin house.
  {% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">

            <p><a href="{% url 'muffinapp:allProdCat' %}">Checkout Our Specials</a></p>
           </div>
        </div>
    </div>
    {% endif %}
<div class="mx_auto">
    {% if category %}
        <img src="{{category.image.url}}" alt="{{category.name}}" height="400px" width="100%">
</div>
    <br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
    {% else %}
<div>
<img src="{% static 'img/banner.png' %}" alt="sweets" width="100%" height="340px">
</div>
<br>
<div>
    <h1 class="text-center my_title">The Muffin House</h1>
    <p class="text-justify">Hello all, this is the website of The Muffin House. The Muffin House is a shop where you can buy all the Sweets you like.We make Custom cakes for Birthday parties, Anniversaries and any other Special Occations.
</div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="200px" height="200px"></a>
            <div>
                <h4>{{product.name}}</h4>
                <p>{{product.description}}</p>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if product.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}> active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

muffinprojects/muffinproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer" style="text-align:center">
    <p>&copy; The Muffin House pvt ltd.All rights Reserved</p>
</div>

muffinprojects/muffinproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'muffinapp:allProdCat' %}"> <img src="{% static 'img/logo.png' %}" alt="logoimage" height="100px" width="140px"></a>
    </center>
</header>

muffinprojects/muffinproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="/">The Muffin House</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{%url 'muffinapp:allProdCat' %}" style="color:red">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Your Cart()</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

muffinprojects/muffinproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:155 }}

{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} -THE MUFFIN HOUSE

  {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'muffinapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" width="300px" height="250px">
        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p class="btn btn-primary">₹ {{product.price}}</p>
            <h4 style="color:grey"><u>Product Description</u></h4>
            <h5>{{product.description}}</h5>
            <p>Do not read this it's just a dummy text. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
            {% if product.stock <= 0 %}
            <p><b>OUT OF STOCK</b></p>
            {% else %}
            <a class="btn btn-secondary" href="/">Add to Cart</a>
            {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}